sudo: required

services:
  - docker

env:
  - DEBUG=1

script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - travis_wait 30 ./docker-images-builder.sh

branches:
  only:
    - master